name: Delete Old Workflow Runs

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at 00:00 UTC
  workflow_dispatch:     # Allow manual trigger from GitHub UI

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Install GitHub CLI and jq
        run: |
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg |
            sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null
          sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | 
            sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh jq -y

      - name: Authenticate and Delete Workflow Runs Older Than 30 Days
        env:
          GH_TOKEN: ${{ secrets.HOMEBREW_TAP_PAT }}
        run: |
          export GITHUB_TOKEN="${GH_TOKEN}"  # Just in case
          REPO="${{ github.repository }}"
          echo "Cleaning up workflow runs for $REPO older than 30 days..."
          gh auth status || {
            echo "GitHub CLI not authenticated. Exiting."
            exit 1
          }
          gh run list --repo "$REPO" --limit 1000 --json databaseId,createdAt,status | \
            jq -c '.[] | select(.status != "in_progress" and (.createdAt | fromdateiso8601 < (now - 30*86400))) | .databaseId' | \
            xargs -r -I % gh run delete % --repo "$REPO" --yes

